POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name":"prueba",
    "email":"jos@gmail.com",
    "password":"123425"
}

###Login sin conexion a base de datos

POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "name": "josprueba",
    "email": "josi@gmail.com",
    "password":"123478"
}

### users
GET http://127.0.0.1:3000/users

